image: ubuntu:jammy

stages:
  - test
  - build
  - deploy

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
dependency_scanning:
  needs: []
license_scanning:
  needs: []

build web:
  stage: build
  image: musicscience37/pipenv:jammy
  needs: []
  scripts:
    - mkdir -p .venv
    - pipenv sync
    - pipenv run python3 ./tool.py build -l ja
  artifacts:
    paths:
      - web/build

pages:
  stage: deploy
  #only:
  #  - main
  needs:
    - build web
  script:
    - mv web/build/ja/html public/ja
    - mv outputs/* public/
    - cp public/KIcon.ico public/favicon.ico
  artifacts:
    paths:
      - public
