image: ubuntu:jammy

stages:
  - test
  - deploy

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
dependency_scanning:
  needs: []
license_scanning:
  needs: []

pages:
  stage: deploy
  #only:
  #  - master
  needs: []
  script:
    - mkdir public
    - mv outputs/* public/
    - cp public/KIcon.ico public/favicon.ico
  artifacts:
    paths:
      - public
