image: ubuntu:18.04

stages:
  - build

build:
  stage: build
  before_script:
    - apt install -y imagemagick
  script:
    - sh convert.sh
  artifacts:
    paths:
      - KIcon.ico
      - KIcon.jpg
      - PNG
