stages:
  - test
  - deploy

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

pages:
  stage: deploy
  image: alpine
  only:
    - main
  script:
    - mv outputs/ public/
    - cp public/KIcon.ico public/favicon.ico
  artifacts:
    paths:
      - public
