[project]
name = "kicon"
version = "0.0.0"
description = ""
readme = "README.md"
authors = [
    { name = "Kenta Kabashima", email = "kenta_program37@hotmail.co.jp" },
]
requires-python = ">=3.12,<3.14"
dependencies = ["click >=8.3.1,<9.0", "setuptools >=80.10.1,<81.0"]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
black = "^26.1.0"
isort = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
