[tool.poetry]
name = "kicon"
version = "0.0.0"
description = ""
authors = ["Kenta Kabashima <kenta_program37@hotmail.co.jp>"]
readme = "README.md"
packages = [{ include = "web/source" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
click = "^8.1.3"
sphinx = "^6.2.0"
sphinx-rtd-theme = "^1.2.1"
sphinxext-opengraph = "^0.8.2"
sphinx-jinja = "^2.0.2"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"
doc8 = "^0.11.2"
sphinx-autobuild = "^2021.3.14"
sphinx-intl = "^2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
